# Configuração para o Netlify (Full-Stack App)
[build]
  command = "npm run build"
  publish = "dist/public"
  functions = "netlify/functions"

# Redirecionar API calls para as funções serverless
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# Redirecionamentos para Single Page Application
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["express"]